language: python
sudo: false
env:
  global:
    secure: "JT8sc+Q57YyDaX1R7ANkOHf/yZqPBu2uiEE4/sBaMV/Mu+SRs+XuRjsNXqsCKAHXkwfY/hdHcCWI+2rY4ngmwvlUaW45rASK5lX0w3RusABpkPbUO4uBDDpVilj34kxKqQR+N11xKR9tbZNhkQhizcIxBbU1xikDoHT4I1SlgERLRQPQ651asu3nrDxyNBysgHe53Tj/8TaQUUZ2f+ruvORwXBXKjGQV51gnQRAmP4SlvNmfYO6AGy/K8CtktzJ2JUR2AHKxARbzGrX/GXmzdlnsovnvcgMs4pmUxPUaFFokKp5kKA75+0xIgYpH4ooeWeGiapD84o3uadS+zQgqiyDqeu0FVNzVrv99ehi8/Y+AXmT7zPFugK+jTCNkH7cDgjuMyTsf3tzPtrtvAQnA53LIMT9JYU0dpx2y6TGflOD9hBRB39J+Li4GpCoufUeW+fG95tBdj4I/2P6pQN0sU35/YAyzVMW5K/jH2uI+fePresqTzOlyMeB4Apcdlp8QOSgxboqhR7zjwCGbStv2bUQ7k5IOkn6O1na0B6CqbznaCfHJID01tqAblkWH3Q+wPxDRc00MI61FkLsUWNM/JVNd/p74ACaUZc/82/KDxwku5ATbfVx0L623xyBx/tICzGh24qYG5BOYEcFO6J2opKLxGVy9+Ox3FHHevFnf95c="

script:
  - pip install requests cryptography
  - echo $a
